const translations = {
    uk: {
        "title": "Закладання розплідника: Керівництво",
        "hero-title": "Закладання розплідника",
        "hero-subtitle": "Практичний посібник зі створення маточника та шкілки",
        "card1-title": "Підготовка та меліорація ґрунту",
        "card1-p": "Окрім бюрократичних процедур, необхідно провести меліорацію (покращення) ґрунту:",
        "card1-li1": "Внесення якісної органічної речовини (щонайменше 4–5 тонн перепрілого гною на гектар).",
        "card1-li2": "Внесення проводиться наприкінці літа під глибоку оранку з подальшим фрезуванням.",
        "card1-li3": "Залежно від хімічного складу ґрунту, слід внести 20 одиниць фосфору та 30 одиниць калію.",
        "card1-li4": "Перед висадкою проводиться друге фрезування для ідеального вирівнювання поверхні.",
        "card2-title": "Планування ділянки",
        "card2-p": "На обраній земельній ділянці відбувається розподіл за рельєфом:",
        "card2-li1": "<strong>Нижня частина:</strong> виділяється під маточні кущі (ceppaie).",
        "card2-li2": "<strong>Верхня частина:</strong> під відібрані відводки/пагони (polloni).",
        "card3-title": "Схема посадки",
        "card3-sub1-title": "Маточні рослини (рослини-донори)",
        "card3-sub1-p": "Висаджуються рядами з міжряддям не менше 2 метрів (краще 2,50 м). Відстань між рослинами в ряду — щонайменше 50 см.",
        "card3-sub2-title": "Ряди відводків (шкілка)",
        "card3-sub2-p": "Відстань між рядами повинна бути не менше 1 метра (краще 1,20 м). Відстань між рослинами в ряду — 20 см.",
        "card4-title": "Посадка та обрізка",
        "card4-li1": "<strong>Глибина загортання:</strong> підземна частина має бути на глибині 20 см. Після усадки ґрунту коренева архітектура сформується на глибині 15 см.",
        "card4-li2": "<strong>Обрізка:</strong> кожен пагін необхідно обрізати на 2–3 см вище другої бруньки над рівнем землі.",
        "card5-title": "Система зрошення",
        "card5-sub1-title": "Для маточників",
        "card5-sub1-p": "Надземна система поливу, підвішена на дроті (кілочки на висоті 1 м) з крапельницями кожні 25 см. Одна крапля падає на рослину, інша — між кущами.",
        "card5-sub2-title": "Для відводків (шкілки)",
        "card5-sub2-p": "Крапельна стрічка розкладається по ряду, періодично переплітаючись між пагонами.",
        "card5-note": "Магістральні трубопроводи можуть бути мобільними або стаціонарними. Вода з озера повинна фільтруватися самоочисним фільтром перед інжекторами Вентурі.",
        "card6-title": "Догляд та живлення",
        "card6-li1": "<strong>Фертигація:</strong> (азот, фосфор, калій) визначається навесні залежно від погоди.",
        "card6-li2": "<strong>Обробіток ґрунту:</strong> механізовано та вручну. <em>Застосування гербіцидів виключається</em> протягом першого року.",
        "card6-li3": "<strong>Захист:</strong> препарати міді, сірки, інсектициди групи піретроїдів. За потреби — специфічні діючі речовини.",
        "card6-li4": "<strong>Підживлення:</strong> листове підживлення для усунення мікродефіцитів.",
        "card7-title": "Збір та зберігання",
        "card7-li1": "<strong>Прискорення визрівання:</strong> обробка сполуками міді перед викопуванням для опадання листя.",
        "card7-li2": "<strong>Сортування:</strong> необхідне закрите приміщення або навіс для обробки рослин та їх підготовки перед відправкою.",
        "card7-li3": "<strong>Зберігання взимку:</strong> у холодильній камері з контролем вологості, або шляхом прикопування (рослини щільними пучками вкладаються у траншею, а коріння ретельно засипається пухким ґрунтом).",
        "footer": "&copy; 2026 Практичне керівництво. Створено з турботою про рослини.",
        "part-title": "Схема створення та функціонування спільного розсадника",
        "part-sec1-title": "1. Суть партнерства та розподіл ролей",
        "part-sec1-p1": "Спільний проєкт базується на синергії технологічного досвіду однієї сторони та ресурсного потенціалу іншої:",
        "part-sec1-li1": "<strong>ТОВ «Віта План» забезпечує:</strong> технологічний супровід, сертифікований садивний матеріал (саджанці/відсадки), розробку систем захисту та живлення.",
        "part-sec1-li2": "<strong>ТОВ «Горіх Полісся» забезпечує:</strong> земельний ресурс (оптимальні легкі ґрунти), людські ресурси для виконання робіт, оперативне та загальне адміністрування бізнесу на місці.",
        "part-sec2-title": "2. Стратегічні переваги для сторін",
        "part-sec2-sub1-title": "ТОВ «Горіх Полісся»",
        "part-sec2-sub1-li1": "<strong>Ефективна зайнятість персоналу:</strong> Раціональне використання та завантаження вже наявного штату працівників підприємства.",
        "part-sec2-sub1-li2": "<strong>Оптимальні ґрунти:</strong> Можливість вирощування культури на легких (піщаних) ґрунтах, що є критичним для розсадництва.",
        "part-sec2-sub1-li3": "<strong>«Друге життя» підприємства:</strong> Диверсифікація діяльності та створення нового потужного вектора розвитку на базі наявної інфраструктури.",
        "part-sec2-sub2-title": "ТОВ «Віта План»",
        "part-sec2-sub2-li1": "<strong>Спеціалізований сортовий склад:</strong> Отримання ексклюзивних, адаптованих сортів, необхідних під конкретні кліматичні умови підприємства.",
        "part-sec2-sub2-li2": "<strong>Взаєморозрахунки матеріалом:</strong> Можливість оперативно отримувати якісні саджанці з розсадника для заміни/ремонту власних площ за внутрішніми домовленостями.",
        "part-sec2-sub2-li3": "<strong>Якість кореневої системи:</strong> Піщана фракція ґрунту дозволяє сформувати ідеальну, розгалужену мичкувату кореневу систему.",
        "part-sec2-note": "<strong>Ключова перевага проєкту:</strong> Розташування розсадника у більш прохолодній частині України забезпечує природне раннє завершення вегетації, що дає унікальну можливість більш раннього викопування та виходу на ринок порівняно з іншими регіонами.",
        "part-sec3-title": "3. Покроковий план реалізації (Дорожня карта)",
        "part-sec3-sub1-title": "Етап І: Проєктування та підготовка",
        "part-sec3-sub1-li1": "<strong>Аудит та вибір ділянки:</strong> Спільний підбір оптимального масиву із земельного фонду ТОВ «Горіх Полісся».",
        "part-sec3-sub1-li2": "<strong>Просторова організація (Зонування):</strong> Виділення площ під ділянки дорощування садивного матеріалу та під маточні насадження (маточник).",
        "part-sec3-sub1-li3": "<strong>Проєктування іригації:</strong> Розробка бюджетного, але високоефективного проєкту системи зрошення із забезпеченням достатнього дебету води.",
        "part-sec3-sub1-li4": "<strong>Підготовка ґрунту:</strong> Проведення комплексу агротехнічних заходів (оранка, фрезування, внесення базових добрив) на обох типах ділянок.",
        "part-sec3-sub2-title": "Етап ІІ: Закладання та монтаж (Весна 2027 року)",
        "part-sec3-sub2-li1": "<strong>Посадка:</strong> Висаджування маточних рослин та висаджування відсадків на дорощування (орієнтир — весна 2027).",
        "part-sec3-sub2-li2": "<strong>Монтаж іригації:</strong> Розгортання та запуск системи поливу безпосередньо після або під час посадки.",
        "part-sec4-title": "4. Юридична та Операційна модель",
        "part-sec4-p1": "Щоб забезпечити легальність, прозорість та коректне формування балансової вартості, взаємодія будується на двох договорах:",
        "diag-box1": "ТОВ «Горіх Полісся»",
        "diag-line1-1": "1. Договір оренди",
        "diag-line1-2": "земельної ділянки",
        "diag-line2-1": "2. Договір на надання послуг",
        "diag-line2-2": "(технічне обслуговування)",
        "diag-box2": "ТОВ «Віта План»",
        "diag-box2-sub": "(Технологія, захист,",
        "diag-box2-sub2": "живлення, облік)",
        "diag-box3": "Виробничі процеси",
        "diag-box3-sub": "(Добрива/ЗЗР за",
        "diag-box3-sub2": "регламентом)",
        "part-sec4-li1": "<strong>Договір оренди:</strong> ТОВ «Горіх Полісся» здає в оренду земельну ділянку для ТОВ «Віта План».",
        "part-sec4-li2": "<strong>Договір на надання послуг:</strong> ТОВ «Горіх Полісся» виступає підрядником, який виконує всі роботи з догляду за насадженнями на замовлення ТОВ «Віта План». Це ключовий інструмент для офіційного включення вартості людських ресурсів та техніки у собівартість саджанця.",
        "part-sec4-li3": "<strong>Агротехнічний регламент:</strong> Систему удобрення та захисту розробляє «Віта План». Виконання (внесення, обробки) чітко за інструкціями здійснює «Горіх Полісся».",
        "part-sec5-title": "5. Фінансовий облік, Сортування та Розподіл прибутку",
        "part-sec5-sub1-title": "Фінансовий моніторинг та Собівартість",
        "part-sec5-sub1-li1": "<strong>Щомісячний облік:</strong> Фіксація витрат (паливо, зарплата, препарати, амортизація) з боку обох компаній.",
        "part-sec5-sub1-li2": "<strong>Поквартальна звітність:</strong> Зведення витрат у єдиний баланс для формування прозорої комерційної собівартості.",
        "part-sec5-sub1-li3": "<strong>Економічна мета:</strong> Балансова (собівартість) ціна має корелювати з ринковою, щоб забезпечити високу маржинальність при реалізації саджанців за цінами 4,50–5 євро.",
        "part-sec5-cost-title": "Нормативи собівартості та дорощування",
        "part-sec5-cost-li1": "<strong>Догляд за саджанцем (1-й рік):</strong> не більше 0,5–0,7 € в перерахунку на один саджанець.",
        "part-sec5-cost-li2": "<strong>Догляд за саджанцем (2-й рік дорощування):</strong> близько 0,5 € на саджанець.",
        "part-sec5-cost-li3": "<strong>Вартість відсадка (відводка):</strong> зафіксувати на рівні 0,25 € за штуку (собівартість після року вирощування в маточному кущі).",
        "part-sec5-sub2-title": "Збір врожаю та Категоризація",
        "part-sec5-sub2-li1": "<strong>Попередній аудит:</strong> Перед початком викопування проводиться інвентаризація та орієнтовний підрахунок кількості наявного матеріалу на полі.",
        "part-sec5-sub2-li2": "<strong>Викопування та градація за сортами:</strong><br>• 1-й сорт: Безпосередній продаж на ринку (ціна продажу: 5 €).<br>• 2-й сорт: Комерційний продаж або закладання на повторне дорощування (ціна продажу: 4,50 €).<br>• 3-й сорт: Виключно дорощування в розсаднику.",
        "part-sec5-sub3-title": "Фінансовий фінал",
        "part-sec5-sub3-li1": "<strong>Розрахунок вартості:</strong> Визначення остаточної вартості отриманого садивного матеріалу.",
        "part-sec5-sub3-li2": "<strong>Реалізація та Чистий прибуток:</strong> Після продажу товарного матеріалу вираховується чиста прибутковість.",
        "part-sec5-sub3-li3": "<strong>Розподіл:</strong> Прибуток ділиться на основі індивідуальних стратегічних домовленостей між Еліо Рессі та Дмитром Дячуком.",
        "part-sec5-sub3-li4": "<strong>Розвиток:</strong> Частина коштів (за потреби) спрямовується на рефінансування, модернізацію або покриття додаткових операційних витрат розсадника.",
        "part-sec6-title": "6. Виробнича програма на 2026-2027 рік",
        "part-sec6-sub1-title": "Осінь 2026 – Весна 2027: Маточник",
        "part-sec6-sub1-li1": "<strong>Висадка:</strong> 150 маточних рослин.",
        "part-sec6-sub1-li2": "<strong>Перспектива:</strong> Після вступу у виробництво (через 3 роки) з них можна буде отримувати близько 3000 саджанців щороку.",
        "part-sec6-sub2-title": "Весна 2027: Імпорт та дорощування",
        "part-sec6-sub2-li1": "<strong>Завезення:</strong> 15 000 відсадків з Румунії для дорощування протягом сезону 2027 року.",
        "part-sec6-sub2-li2": "<strong>Реалізація:</strong> Продаж готових саджанців восени 2027 року або навесні 2028 року.",
        "part-sec6-sub3-title": "Осінь 2027: Викопування та сортування",
        "part-sec6-sub3-p": "Очікуваний розподіл завезених відсадків після дорощування:",
        "part-sec6-sub3-li1": "<strong>60%</strong> — Товарні саджанці для продажу (ціна: 4,5 € з ПДВ).",
        "part-sec6-sub3-li2": "<strong>20%</strong> — Саджанці 3-го сорту (залишаються на повторне дорощування).",
        "part-sec6-sub3-li3": "<strong>20%</strong> — Природний відпад (загибель рослин у процесі дорощування та приживання).",
        "part-sec6-sub4-title": "Схема розподілу прибутку",
        "part-sec6-sub4-formula": "<strong>Формула (базова):</strong><br>( (Сума від продажу — Витрати «Горіх Полісся» — Витрати «Віта План») — 10% від чистого прибутку ) ÷ 2",
        "part-sec6-sub4-p": "<em>Альтернативний варіант:</em> Прибуток може розподілятися у відсотковому співвідношенні, пропорційно до суми понесених витрат кожною із сторін.",
        "part-sec6-sub5-title": "Фінансова модель: Дорощування саджанців",
        "part-sec6-sub5-p1": "Розрахунок прибутковості розсадницького напрямку на прикладі партії з 15 000 відсадків:",
        "part-sec6-sub5-li1": "<strong>Закупівля матеріалу:</strong> 15 000 шт. × 1,20 € = 18 000 €",
        "part-sec6-sub5-li2": "<strong>Витрати на догляд:</strong> ~0,60 € (середнє) на 15 000 рослин = ~9 000 €",
        "part-sec6-sub5-li3": "<strong>Очікуваний дохід:</strong> 9 000 товарних саджанців (60% виходу) × 4,50 € = 40 500 €",
        "part-sec6-sub5-li4": "<strong>Комісія (10% від прибутку):</strong> (40 500 € - 18 000 € - 9 000 €) × 10% = 1 350 € (за продажі)",
        "part-sec6-sub5-li5": "<strong>Орієнтовний прибуток до розподілу:</strong> 13 500 € - 1 350 € = <strong>12 150 €</strong> <em>(додатково залишається 3000 саджанців 3-го сорту)</em>.",
        "part-sec6-sub6-title": "Інвестиції: Маточне насадження",
        "part-sec6-sub6-li1": "<strong>Закупівля рослин:</strong> 150 маточних кущів × 7,00 € = 1 050 €",
        "part-sec6-sub6-li2": "<strong>Специфіка догляду:</strong> Маточник потребує регулярного догляду та інвестицій протягом <strong>3 років</strong>.",
        "part-sec6-sub6-li3": "<strong>Перспектива:</strong> Лише через 3 роки маточник вступить у повноцінне виробництво, після чого з нього можна буде розпочати відділення перших власних відсадків (орієнтовно 3000 шт. щороку)."
    },
    it: {
        "title": "Impianto del vivaio: Guida",
        "hero-title": "Impianto del vivaio",
        "hero-subtitle": "Guida pratica per la creazione di un vivaio (ceppaie e barbatelle)",
        "card1-title": "Preparazione e miglioramento del terreno",
        "card1-p": "Oltre alle procedure burocratiche, è necessario migliorare (bonificare) il terreno:",
        "card1-li1": "Apporto di sostanza organica di qualità (almeno 4–5 tonnellate di letame maturo per ettaro).",
        "card1-li2": "L'apporto si effettua a fine estate con un'aratura profonda seguita da fresatura.",
        "card1-li3": "A seconda della composizione chimica del terreno, si devono aggiungere 20 unità di fosforo e 30 unità di potassio.",
        "card1-li4": "Subito prima dell'impianto, si esegue una seconda fresatura per livellare perfettamente la superficie.",
        "card2-title": "Pianificazione del terreno",
        "card2-p": "Nell'area selezionata, il terreno viene suddiviso in base al rilievo:",
        "card2-li1": "<strong>Parte inferiore:</strong> destinata alle piante madri (ceppaie).",
        "card2-li2": "<strong>Parte superiore:</strong> destinata ai polloni selezionati.",
        "card3-title": "Sesto di impianto",
        "card3-sub1-title": "Piante madri (donatrici)",
        "card3-sub1-p": "Piantate in filari con una distanza interfilare di almeno 2 metri (meglio 2,50 m). La distanza tra le piante sulla fila deve essere di almeno 50 cm.",
        "card3-sub2-title": "Filari di polloni (barbatelle)",
        "card3-sub2-p": "La distanza tra i filari deve essere di almeno 1 metro (meglio 1,20 m). La distanza tra le piante sulla fila è di 20 cm.",
        "card4-title": "Impianto e potatura",
        "card4-li1": "<strong>Profondità di interramento:</strong> la parte sotterranea deve trovarsi a 20 cm di profondità. Successivamente, dopo l'assestamento del terreno, l'architettura radicale si formerà a 15 cm di profondità.",
        "card4-li2": "<strong>Potatura:</strong> ogni germoglio deve essere potato a 2-3 cm sopra la seconda gemma sopra il livello del suolo.",
        "card5-title": "Sistema di irrigazione",
        "card5-sub1-title": "Per le ceppaie",
        "card5-sub1-p": "Sistema di irrigazione fuori terra, sospeso su un filo (picchetti ad altezza 1 m) con gocciolatori ogni 25 cm. Una goccia cadrà sulla pianta, l'altra in mezzo tra i due cespugli.",
        "card5-sub2-title": "Per i polloni",
        "card5-sub2-p": "L'ala gocciolante viene stesa lungo la fila, intrecciandosi periodicamente tra i germogli.",
        "card5-note": "Le condotte principali possono essere mobili o fisse. L'acqua proveniente dal lago (bacino di accumulo) deve essere filtrata da un filtro autopulente posto subito prima degli iniettori Venturi.",
        "card6-title": "Cura e nutrizione",
        "card6-li1": "<strong>Fertirrigazione:</strong> (azoto, fosforo, potassio) sarà determinata in primavera a seconda delle condizioni climatiche.",
        "card6-li2": "<strong>Lavorazione del terreno:</strong> da eseguire sia meccanicamente che manualmente. <em>L'uso di diserbanti è completamente escluso</em> durante il primo anno.",
        "card6-li3": "<strong>Protezione delle piante:</strong> preparati a base di rame, zolfo, insetticidi del gruppo dei piretroidi e, se necessario, principi attivi specifici.",
        "card6-li4": "<strong>Nutrizione fogliare:</strong> può essere utilizzata per eliminare micro-carenze e stimolare la vegetazione.",
        "card7-title": "Raccolta e conservazione",
        "card7-li1": "<strong>Accelerazione della maturazione:</strong> prima dello scavo, si può accelerare la maturazione del legno e la caduta delle foglie con trattamenti a base di rame.",
        "card7-li2": "<strong>Cernita:</strong> è necessario un ambiente chiuso o almeno una tettoia per la cernita, la lavorazione e la preparazione delle piante prima della spedizione.",
        "card7-li3": "<strong>Conservazione invernale:</strong> in una cella frigorifera a umidità controllata, oppure tramite interramento (le piante vengono disposte a fasci stretti in una trincea e le radici vengono accuratamente ricoperte con terreno sciolto).",
        "footer": "&copy; 2026 Guida pratica. Creata con cura per le piante.",
        "part-title": "Schema di creazione e funzionamento del vivaio congiunto",
        "part-sec1-title": "1. Essenza della partnership e distribuzione dei ruoli",
        "part-sec1-p1": "Il progetto congiunto si basa sulla sinergia tra l'esperienza tecnologica di una parte e il potenziale delle risorse dell'altra:",
        "part-sec1-li1": "<strong>La «Vita Plan» srl fornisce:</strong> supporto tecnologico, materiale di piantagione certificato (piante/polloni), sviluppo di sistemi di protezione e nutrizione.",
        "part-sec1-li2": "<strong>La «Gorikh Polissya» srl fornisce:</strong> risorse terriere (terreni leggeri ottimali), risorse umane per l'esecuzione dei lavori, amministrazione operativa e generale del business in loco.",
        "part-sec2-title": "2. Vantaggi strategici per le parti",
        "part-sec2-sub1-title": "La «Gorikh Polissya» srl",
        "part-sec2-sub1-li1": "<strong>Occupazione efficace del personale:</strong> Uso razionale e impiego del personale già esistente dell'azienda.",
        "part-sec2-sub1-li2": "<strong>Terreni ottimali:</strong> Possibilità di coltivare su terreni leggeri (sabbiosi), fondamentale per il vivaismo.",
        "part-sec2-sub1-li3": "<strong>«Seconda vita» dell'azienda:</strong> Diversificazione delle attività e creazione di un nuovo forte vettore di sviluppo basato sull'infrastruttura esistente.",
        "part-sec2-sub2-title": "La «Vita Plan» srl",
        "part-sec2-sub2-li1": "<strong>Composizione varietale specializzata:</strong> Ottenimento di varietà esclusive e adattate necessarie per le specifiche condizioni climatiche dell'azienda.",
        "part-sec2-sub2-li2": "<strong>Compensazione con materiale:</strong> Possibilità di ricevere rapidamente piantine di qualità dal vivaio per la sostituzione/riparazione delle proprie aree secondo accordi interni.",
        "part-sec2-sub2-li3": "<strong>Qualità del sistema radicale:</strong> La frazione sabbiosa del terreno consente di formare un sistema radicale fascicolato ideale e ramificato.",
        "part-sec2-note": "<strong>Vantaggio chiave del progetto:</strong> La posizione del vivaio nella parte più fresca dell'Ucraina assicura una fine naturale precoce della stagione di crescita, che offre un'opportunità unica per uno scavo più precoce e l'ingresso sul mercato rispetto ad altre regioni.",
        "part-sec3-title": "3. Piano di realizzazione (Tabella di marcia)",
        "part-sec3-sub1-title": "Fase I: Progettazione e preparazione",
        "part-sec3-sub1-li1": "<strong>Audit e selezione del sito:</strong> Selezione congiunta dell'area ottimale dal fondo rustico della «Gorikh Polissya» srl.",
        "part-sec3-sub1-li2": "<strong>Organizzazione spaziale (Zonizzazione):</strong> Assegnazione di aree per le sezioni di crescita del materiale di piantagione e per le piantagioni madri (ceppaie).",
        "part-sec3-sub1-li3": "<strong>Progettazione dell'irrigazione:</strong> Sviluppo di un progetto di sistema di irrigazione a basso costo ma ad alta efficienza per garantire una sufficiente portata d'acqua.",
        "part-sec3-sub1-li4": "<strong>Preparazione del terreno:</strong> Esecuzione di una serie di misure agrotecniche (aratura, fresatura, applicazione di fertilizzanti di base) su entrambi i tipi di aree.",
        "part-sec3-sub2-title": "Fase II: Posa e installazione (Primavera 2027)",
        "part-sec3-sub2-li1": "<strong>Piantagione:</strong> Piantagione di piante madri e polloni per la crescita (obiettivo — primavera 2027).",
        "part-sec3-sub2-li2": "<strong>Installazione dell'irrigazione:</strong> Implementazione e avvio del sistema di irrigazione immediatamente dopo o durante la piantagione.",
        "part-sec4-title": "4. Modello Giuridico e Operativo",
        "part-sec4-p1": "Per garantire legalità, trasparenza e la corretta formazione del valore di bilancio, l'interazione si basa su due contratti:",
        "diag-box1": "La «Gorikh Polissya» srl",
        "diag-line1-1": "1. Contratto di affitto",
        "diag-line1-2": "del terreno",
        "diag-line2-1": "2. Contratto per la fornitura",
        "diag-line2-2": "di servizi (manutenzione)",
        "diag-box2": "La «Vita Plan» srl",
        "diag-box2-sub": "(Tecnologia, protezione,",
        "diag-box2-sub2": "nutrizione, contabilità)",
        "diag-box3": "Processi di produzione",
        "diag-box3-sub": "(Fertilizzanti/Fitofarmaci",
        "diag-box3-sub2": "secondo regolamento)",
        "part-sec4-li1": "<strong>Contratto di affitto:</strong> La «Gorikh Polissya» srl affitta il terreno alla «Vita Plan» srl.",
        "part-sec4-li2": "<strong>Contratto per la fornitura di servizi:</strong> La «Gorikh Polissya» srl agisce come appaltatore, eseguendo tutti i lavori di cura delle piantagioni commissionati dalla «Vita Plan» srl. Questo è lo strumento chiave per includere ufficialmente il costo delle risorse umane e dei macchinari nel costo di produzione della piantina.",
        "part-sec4-li3": "<strong>Regolamento agrotecnico:</strong> Il sistema di fertilizzazione e protezione è sviluppato dalla «Vita Plan». L'esecuzione (applicazione, trattamenti) è rigorosamente eseguita dalla «Gorikh Polissya» secondo le istruzioni.",
        "part-sec5-title": "5. Contabilità finanziaria, Selezione e Distribuzione",
        "part-sec5-sub1-title": "Monitoraggio finanziario e Costo di produzione",
        "part-sec5-sub1-li1": "<strong>Contabilità mensile:</strong> Registrazione delle spese (carburante, stipendi, preparati, ammortamento) da parte di entrambe le aziende.",
        "part-sec5-sub1-li2": "<strong>Rendicontazione trimestrale:</strong> Consolidamento delle spese in un unico bilancio per formare un costo commerciale trasparente.",
        "part-sec5-sub1-li3": "<strong>Obiettivo economico:</strong> Il prezzo di bilancio (costo) deve essere correlato al mercato per garantire un alto margine nella vendita di piantine a prezzi di 4,50–5 euro.",
        "part-sec5-cost-title": "Standard di costo e di accrescimento",
        "part-sec5-cost-li1": "<strong>Cura della piantina (1° anno):</strong> non più di 0,5-0,7 € per singola piantina.",
        "part-sec5-cost-li2": "<strong>Cura della piantina (2° anno di accrescimento):</strong> circa 0,5 € per piantina.",
        "part-sec5-cost-li3": "<strong>Costo della barbatella (pollone):</strong> fissato a 0,25 € al pezzo (costo di produzione dopo un anno di crescita nella ceppaia madre).",
        "part-sec5-sub2-title": "Raccolta e Categorizzazione",
        "part-sec5-sub2-li1": "<strong>Audit preliminare:</strong> Prima dell'escavazione, viene effettuato un inventario e una stima approssimativa della quantità di materiale disponibile sul campo.",
        "part-sec5-sub2-li2": "<strong>Escavazione e classificazione:</strong><br>• 1ª scelta: Vendita diretta sul mercato (prezzo di vendita: 5 €).<br>• 2ª scelta: Vendita commerciale o reimpianto per ulteriore crescita (prezzo di vendita: 4,50 €).<br>• 3ª scelta: Esclusivamente ulteriore crescita nel vivaio.",
        "part-sec5-sub3-title": "Finale Finanziario",
        "part-sec5-sub3-li1": "<strong>Calcolo del valore:</strong> Determinazione del valore finale del materiale ottenuto.",
        "part-sec5-sub3-li2": "<strong>Vendita e Utile netto:</strong> Dopo la vendita del materiale commerciale, viene calcolata la redditività netta.",
        "part-sec5-sub3-li3": "<strong>Distribuzione:</strong> Il profitto viene diviso in base agli accordi strategici individuali tra Elio Ressi e Dmytro Dyachuk.",
        "part-sec5-sub3-li4": "<strong>Sviluppo:</strong> Una parte dei fondi (se necessario) viene indirizzata al rifinanziamento, all'ammodernamento o alla copertura di ulteriori spese operative del vivaio.",
        "part-sec6-title": "6. Programma di produzione per il 2026-2027",
        "part-sec6-sub1-title": "Autunno 2026 – Primavera 2027: Piante madri",
        "part-sec6-sub1-li1": "<strong>Piantagione:</strong> 150 piante madri (ceppaie).",
        "part-sec6-sub1-li2": "<strong>Prospettiva:</strong> Dopo l'entrata in produzione (tra 3 anni) sarà possibile ottenere circa 3000 piantine all'anno.",
        "part-sec6-sub2-title": "Primavera 2027: Importazione e accrescimento",
        "part-sec6-sub2-li1": "<strong>Importazione:</strong> 15.000 polloni dalla Romania per l'accrescimento durante la stagione 2027.",
        "part-sec6-sub2-li2": "<strong>Vendita:</strong> Vendita delle piantine pronte nell'autunno 2027 o nella primavera 2028.",
        "part-sec6-sub3-title": "Autunno 2027: Escavazione e selezione",
        "part-sec6-sub3-p": "Distribuzione prevista dei polloni importati dopo l'accrescimento:",
        "part-sec6-sub3-li1": "<strong>60%</strong> — Piantine commerciali per la vendita (prezzo: 4,5 € IVA inclusa).",
        "part-sec6-sub3-li2": "<strong>20%</strong> — Piantine di 3ª scelta (destinate a ulteriore accrescimento nel vivaio).",
        "part-sec6-sub3-li3": "<strong>20%</strong> — Mortalità naturale (durante l'accrescimento e l'attecchimento).",
        "part-sec6-sub4-title": "Schema di distribuzione degli utili",
        "part-sec6-sub4-formula": "<strong>Formula (base):</strong><br>( (Ricavo vendite — Spese «Gorikh Polissya» — Spese «Vita Plan») — 10% dell'utile netto ) ÷ 2",
        "part-sec6-sub4-p": "<em>Alternativa:</em> Il profitto può essere distribuito in percentuale proporzionale all'importo delle spese sostenute da ciascuna parte.",
        "part-sec6-sub5-title": "Modello Finanziario: Accrescimento Piantine",
        "part-sec6-sub5-p1": "Calcolo della redditività del settore vivaistico sull'esempio di 15.000 polloni:",
        "part-sec6-sub5-li1": "<strong>Acquisto del materiale:</strong> 15.000 pz × 1,20 € = 18.000 €",
        "part-sec6-sub5-li2": "<strong>Costi di manutenzione:</strong> ~0,60 € (media) per 15.000 piante = ~9.000 €",
        "part-sec6-sub5-li3": "<strong>Ricavo previsto:</strong> 9.000 piantine commerciali (resa 60%) × 4,50 € = 40.500 €",
        "part-sec6-sub5-li4": "<strong>Commissione (10% dell'utile):</strong> (40.500 € - 18.000 € - 9.000 €) × 10% = 1.350 € (per vendite)",
        "part-sec6-sub5-li5": "<strong>Utile stimato da distribuire:</strong> 13.500 € - 1.350 € = <strong>12.150 €</strong> <em>(inoltre, rimangono 3000 piantine di 3ª scelta)</em>.",
        "part-sec6-sub6-title": "Investimenti: Piante Madri",
        "part-sec6-sub6-li1": "<strong>Acquisto piante:</strong> 150 ceppaie madri × 7,00 € = 1.050 €",
        "part-sec6-sub6-li2": "<strong>Cura specifica:</strong> Il campo madri richiede cure costanti e investimenti per <strong>3 anni</strong>.",
        "part-sec6-sub6-li3": "<strong>Prospettiva:</strong> Solo dopo 3 anni le piante madri entreranno in piena produzione, dopodiché sarà possibile iniziare la separazione dei primi polloni (circa 3000 pz all'anno)."
    }
};

document.addEventListener("DOMContentLoaded", () => {
    // Animation Logic
    const fadeElements = document.querySelectorAll('.fade-in');
    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('visible');
                observer.unobserve(entry.target);
            }
        });
    }, { 
        threshold: 0.1,
        rootMargin: "0px 0px -50px 0px"
    });

    fadeElements.forEach(el => observer.observe(el));

    // Translation Logic
    const langBtns = document.querySelectorAll('.lang-btn');
    
    function setLanguage(lang) {
        document.documentElement.lang = lang;
        
        // Update texts
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (translations[lang] && translations[lang][key]) {
                el.innerHTML = translations[lang][key];
            }
        });

        // Update active button
        langBtns.forEach(btn => {
            if (btn.getAttribute('data-lang') === lang) {
                btn.classList.add('active');
            } else {
                btn.classList.remove('active');
            }
        });
    }

    langBtns.forEach(btn => {
        btn.addEventListener('click', (e) => {
            const lang = e.target.getAttribute('data-lang');
            setLanguage(lang);
        });
    });
});
